# Generated by Django 4.1.5 on 2023-02-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ParkingSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.IntegerField()),
                ("spot_number", models.IntegerField()),
                ("occupied", models.BooleanField(default=False)),
            ],
        ),
    ]
